#!/bin/bash

sudo add-apt-repository -y ppa:mozillateam/ppa
sudo cp mozillateamppa /etc/apt/preferences.d
sudo cp 51unattended-upgrades-firefox /etc/apt/apt.conf.d
sudo apt update
sudo apt install -y firefox firefox-locale-fr